apiVersion: v1
kind: Service
metadata:
  name: aidfit-backend-svc
  namespace: aidfit
spec:
  selector:
    app: aidfit-backend
  ports:
    - name: http
      port: 12570
      targetPort: 8000
  type: LoadBalancer

